name: release
permissions:
  contents: write
  checks: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version to release'
        required: true
        type: choice
        default: patch
        options:
          - patch
          - rc
          - minor
          - beta
          - alpha
          - major
          - release
      runner:
        description: 'Runner to use'
        required: false
jobs:
  releaser:
    if: false
    name: release
    uses: ./.github/workflows/rust-release.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      package: 'dummy'
