name: Pages
permissions:
  contents: write # To push a branch
  pages: write # To push to a GitHub Pages site
  id-token: write # To update the deployment status
on:
  workflow_call:

jobs:
  config:
    runs-on: ${{ vars.RUNNER }}
    name: generate config
    outputs:
      config: ${{ steps.merge.outputs.config }}
    steps:
      - name: merge
        id: merge
        uses: kiro-generator/ci/.github/actions/rust-config@cache-nonsense
        with:
          git_token: ${{ github.token }}
  mdbook:
    runs-on: ${{ vars.RUNNER }}
    needs: ['config']
    if: ${{ fromJSON(needs.config.outputs.config).pages.mdbook.if }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/cache@v5
        with:
          path: ./mdbook
          key: mdbook-v0.5.2-arm64
      - name: Install mdbook
        run: |
          if [ ! -f ./mdbook ]; then
            wget https://github.com/rust-lang/mdBook/releases/download/v0.5.2/mdbook-v0.5.2-aarch64-unknown-linux-musl.tar.gz
            tar zxf mdbook-*.tar.gz
          fi
          ./mdbook build ./docs
          echo $PATH
          sudo cp mdbook /usr/local/bin
      - name: Build Book
        run: |
          cd ${{ fromJSON(needs.config.outputs.config).pages.mdbook.path }}
          ${{ fromJSON(needs.config.outputs.config).pages.mdbook.command }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ fromJSON(needs.config.outputs.config).pages.mdbook.path }}/book
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
