name: Pages
permissions:
  contents: write # To push a branch
  pages: write # To push to a GitHub Pages site
  id-token: write # To update the deployment status
on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ${{ vars.RUNNER }}
        required: false

jobs:
  config:
    runs-on: ubicloud-standard-2
    name: generate config
    outputs:
      config: ${{ steps.merge.outputs.config }}
    steps:
      - name: merge
        id: merge
        uses: carteramesh/ci/.github/actions/rust-config@main
        with:
          git_token: ${{ github.token }}
          runner: ${{ inputs.runner }}
  mdbook:
    runs-on: ubicloud-standard-2
    needs: ['config']
    if: ${{ fromJSON(needs.config.outputs.config).pages.mdbook.if }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      # - name: Install latest mdbook
      #   run: |
      #     tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
      #     url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-aarch64-unknown-linux-gnu.tar.gz"
      #     mkdir mdbook
      #     curl -sSL $url | tar -xz --directory=./mdbook
      #     echo `pwd`/mdbook >> $GITHUB_PATH
      - uses: jontze/action-mdbook@v4
        name: Install mdBook
        with:
          token: ${{secrets.GITHUB_TOKEN}}
      - name: Build Book
        run: |
          cd ${{ fromJSON(needs.config.outputs.config).pages.mdbook.path }}
          ${{ fromJSON(needs.config.outputs.config).pages.mdbook.command }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ fromJSON(needs.config.outputs.config).pages.mdbook.path }}/book
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
