name: ci lib release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ vars.RUNNER }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Configure npm registry
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Build
        run: bun install && bun run build
      - name: Get version
        id: version
        run: echo "tag=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      # - name: Publish
        # run: bun publish --access public
      - name: Publish to npm
        run: npm publish
      - uses: softprops/action-gh-release@v2
        name: publish
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
