name: ci lib release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ vars.RUNNER }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: oven-sh/setup-bun@v2

      - name: Configure npm registry
        run: |
          echo "@dougefresh:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Build
        run: bun run build
      - name: Get version
        id: version
        run: echo "tag=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Publish to GitHub Packages
        run: bun publish

      - uses: softprops/action-gh-release@v2
        name: publish
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          generate_release_notes: true
