name: Rust Check
on:
  workflow_call:
    inputs:
      ubuntu_packages:
        type: string
        required: false
        default: ""
      toolchains:
        type: string
        required: false
        default: '["stable","nightly"]'
      features:
        type: string
        required: false
        default: '["default"]'
      extra_script_path:
        type: string
        default: ".github/ci-scripts/extra.sh"
        required: false
      runner:
        type: string
        default: ${{ vars.RUNNER }}
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ${{ inputs.runner }}
    name: nightly fmt
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: cargo fmt --check
        run: |
          cargo +nightly fmt --check --all
  clippy:
    runs-on: ${{ inputs.runner }}
    name: ${{ matrix.toolchain }} / clippy / ${{ matrix.features }}
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: ${{ fromJSON(inputs.toolchains) }}
        features: ${{ fromJSON(inputs.features) }}
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ inputs.ubuntu_packages }}
      # - name: ${{ matrix.toolchain }} cargo clippy (${{ matrix.features }})
      #   shell: bash
      #   run: |
      #     f=${{ matrix.features != 'default' && format('--features {0}', matrix.features) || '' }}
      #     cargo +${{ matrix.toolchain }} clippy --all-targets $f -- -D warnings
      - name: ${{ matrix.toolchain }} cargo clippy (${{ matrix.features }})
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-check"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: clippy-${{ matrix.features }}
          clippy_flags: ${{ matrix.features != 'default' && format('--features {0}', matrix.features) || '' }}
  semver:
    runs-on: ${{ inputs.runner }}
    name: semver
    if: true
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ inputs.ubuntu_packages }}
      - name: cargo-semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        # with:
        # feature-group: ${{ matrix.features != 'default' && matrix.features || 'default-features' }}

  hack:
    # cargo-hack checks combinations of feature flags to ensure that features are all additive
    # which is required for feature unification
    runs-on: ${{ inputs.runner }}
    name: hack
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ inputs.ubuntu_packages }}
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      # intentionally no target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      # --feature-powerset runs for every combination of features
      - name: cargo hack
        run: cargo hack --feature-powerset check

  doc:
    runs-on: ${{ inputs.runner }}
    name: doc
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
        with:
          ubuntu_packages: ${{ inputs.ubuntu_packages }}
      - name: cargo docs-rs
        run: |
          cargo +nightly docs-rs

  cargo_sort:
    runs-on: ${{ inputs.runner }}
    name: cargo-sort
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: Check `Cargo.toml` sort
        run: |
          if [ -f ./scripts/cargo-sort.sh ]; then
            ./scripts/cargo-sort.sh
          else
            cargo sort -c -g
          fi

  dependencies:
    runs-on: ${{ inputs.runner }}
    name: check unused deps
    steps:
      - name: Init
        uses: carteramesh/ci/.github/actions/rust-init@main
      - name: cargo-udeps
        if: false
        run: |
          cargo +nightly install cargo-udeps
          cargo +nightly udeps  --all-targets  --workspace
      - name: Check unused Cargo dependencies
        run: cargo machete
